apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-frontend
  namespace: default
  labels:
    app.kubernetes.io/part-of: blackjack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: blackjack
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: blackjack
    spec:
      containers:
      - env:
        - name: VIDEO_INPUT
          value: "0"
        - name: ACCELERATION_DEVICE
          value: CPU
        - name: AMQP_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: host
              name: edge-inferencing-events-default-user
              optional: true
        - name: AMQP_PORT
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: port
              optional: true
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: username
              optional: true
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edge-inferencing-events-default-user
              key: password
              optional: true
        image: mwrightpivotal/openvino_notebooks:ovrun
        name: workload
        securityContext:
          runAsUser: 0
        resources:
          limits:
            squat.ai/serial: "1"
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: blackjack
  namespace: default
  labels:
    app.kubernetes.io/part-of: blackjack
spec:
  selector:
    app.kubernetes.io/part-of: blackjack
  type: NodePort
  ports:
  - targetPort: 8888
    port: 8888
    name: http
    nodePort: 30009

