apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: photon-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-xsmall
  imageName: packages.vmware.com/photon/4.0/GA/ova/photon-hw11-4.0-1526e30ba0.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-photon
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-photon
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: root
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: '$6$rounds=4096$1G8o7yMmuIExwmJL$Z2U9EexAf8FG/7UHeut1NwvQyeBxSjqqgEgxuNOKQmKjBVMZWUhfvjh/BkQAFARD5zDo1puWSySlXp/IhijxL/'
        shell: /bin/bash
    write_files:
      - content: |
          Keswick VM service says Hello World
        path: /helloworld
